name: "Index datapackage"
description: "Installs a package and runs a python script"
inputs:
  token:
    description: 'A Github PAT'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dotoenv
      shell: bash
      run: pip3 install python-dotenv
    - name: Install frictionless
      shell: bash
      run: pip3 install frictionless
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::561987031915:role/github-actions
        aws-region: us-east-1
    - name: Copy data from S3 and Validate
      shell: bash
      continue-on-error: true
      run: | 
        S3_KEY=$(python .github/datahub-gh-actions/validate-data/get_key.py)
        aws s3 cp s3://datopian-datahub/$(echo $S3_KEY) data.csv
        FRICTIONLESS_OUTPUT=$(frictionless validate data.csv)
        printf "$FRICTIONLESS_OUTPUT"
        echo 'COMMIT_BODY<<EOF' >> $GITHUB_ENV
        echo "$FRICTIONLESS_OUTPUT" >> $GITHUB_ENV
        echo '\n' >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Make a comment in the commit page
      uses: peter-evans/commit-comment@v2
      with:
        body: |
          ```
          ${{ env.COMMIT_BODY }}
          ```
        token: ${{inputs.token}}
    - name: Success if valid, error if invalid data
      shell: python
      run: |
        from frictionless import validate

        report = validate('data.csv')
        if report['valid'] == False:
          exit(1)
