name: "Index datapackage"
description: "Installs a package and runs a python script"
runs:
  using: "composite"
  steps:
    - name: Install dotoenv
      shell: bash
      run: pip3 install python-dotenv
    - name: Install frictionless
      shell: bash
      run: pip3 install frictionless
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::561987031915:role/github-actions
        aws-region: us-east-1
    - name: Copy data from S3 and Validate
      shell: bash
      run: | 
        S3_KEY=$(python .github/datahub-gh-actions/validate-data/get_key.py)
        echo "Copying data from..."
        echo $S3_KEY 
        aws s3 cp s3://datopian-datahub/$(echo $S3_KEY) data.csv
        frictionless validate data.csv
