name: "Index datapackage"
description: "Installs a package and runs a python script"
inputs:
  token:
    description: 'A Github PAT'
    required: true
  user:
    description: 'AWS User ARN'
    required: true
  region:
    description: 'AWS S3 Bucket Region'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dotoenv
      shell: bash
      run: pip3 install python-dotenv
    - name: Install frictionless
      shell: bash
      run: pip3 install frictionless
    - name: Get S3 Key
      id: get-s3-key
      shell: bash
      run: |
        S3_KEY=$(python .github/datahub-gh-actions/validate-data/get_key.py)
        echo "S3_KEY=$S3_KEY" >> $GITHUB_OUTPUT
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{inputs.user}}
        aws-region: ${{inputs.region}}
    - name: Copy data from S3 and Validate
      shell: bash
      continue-on-error: true
      if: ${{ contains(steps.get-s3-key.outputs.S3_KEY, '__NoKey__') != true }}
      run: | 
        aws s3 cp s3://datopian-datahub/$(echo ${{ steps.get-s3-key.outputs.S3_kEY }}) data.csv
        FRICTIONLESS_OUTPUT=$(frictionless validate data.csv || true)
        echo 'COMMIT_BODY<<EOF' >> $GITHUB_ENV
        echo "$FRICTIONLESS_OUTPUT" >> $GITHUB_ENV
        echo '\n' >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Make a comment in the commit page
      uses: peter-evans/commit-comment@v2
      if: ${{ contains(steps.get-s3-key.outputs.S3_KEY, '__NoKey__') != true }}
      with:
        body: |
          ```
          ${{ env.COMMIT_BODY }}
          ```
        token: ${{inputs.token}}
    - name: Success if valid, error if invalid data
      if: ${{ contains(steps.get-s3-key.outputs.S3_KEY, '__NoKey__') != true }}
      shell: python
      run: |
        from frictionless import validate

        report = validate('data.csv')
        if report['valid'] == False:
          exit(1)
