name: "Index datapackage"
description: "Installs a package and runs a python script"
runs:
  using: "composite"
  steps:
    - name: Install dotoenv
      shell: bash
      run: pip3 install python-dotenv
    - name: Run Python Script
      shell: bash
      run: | 
        S3_KEY=$(python .github/datahub-gh-actions/validate-data/get_key.py)
        echo $S3_KEY
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::561987031915:role/github-actions
        aws-region: us-east-1

