name: "Validate metadata"
description: "Validate a datapackage file"
runs:
  using: "composite"
  steps:
    - name: Install dotoenv
      shell: bash
      run: pip3 install python-dotenv
    - name: Install datapackage
      shell: bash
      run: pip3 install datapackage
    - name: Run Python Script
      shell: python
      run: |
        import sys
        import os
        from datapackage import validate, exceptions

        from dotenv import load_dotenv

        load_dotenv()

        def main():
            if os.getenv('DATASET_NAME') is None:
                raise Exception("Lacking a filename argument")
            filename = os.getenv('DATASET_NAME')
            full_path = f"/home/runner/work/{os.getenv('REPO_NAME')}/{os.getenv('REPO_NAME')}/datasets/{filename}/datapackage.json"
            try:
              valid = validate(full_path)
            except exceptions.ValidationError as exception:
              for error in exception.errors:
              raise error

        main()
