name: "Validate metadata"
description: "Validate a datapackage file"
inputs:
  token:
    description: "A Github PAT"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dotoenv
      shell: bash
      run: pip3 install python-dotenv
    - name: Install datapackage
      shell: bash
      run: pip3 install datapackage
    - name: Get validation output
      shell: bash
      continue-on-error: true
      run: |
        FRICTIONLESS_OUTPUT=$(python .github/datahub-gh-actions/validate-metadata/validate.py || true)
        echo 'COMMIT_BODY<<EOF' >> $GITHUB_ENV
        echo "$FRICTIONLESS_OUTPUT" >> $GITHUB_ENV
        echo '\n' >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Validate and error throw if error
      shell: bash
      id: validate
      continue-on-error: true
      run: |
        python .github/datahub-gh-actions/validate-metadata/validate.py
    - name: Make a comment in the commit page
      if: ${{ failure() && steps.validate.outcome == 'failure' }}
      uses: peter-evans/commit-comment@v2
      with:
        body: |
          ```
          ${{ env.COMMIT_BODY }}
          ```
        token: ${{inputs.token}}
